import '@/styles/globals.css';
import '@/styles/nprogress.css';
import Router from 'next/router';

import { motion } from 'framer-motion';
import NProgress from 'nprogress';
import Head from 'next/head';

function MyApp({ Component, pageProps, router }) {
  Router.events.on('routeChangeStart', () => NProgress.start());
  Router.events.on('routeChangeComplete', () => NProgress.done());
  Router.events.on('routeChangeError', () => NProgress.done());

  return (
    <>
      <Head>
        <title>Next Practices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        key={router.route}
        initial={'pageInitial'}
        animate={'pageAnimate'}
        variants={{
          pageInitial: {
            opacity: 0,
          },
          pageAnimate: {
            opacity: 1,
          },
        }}
      >
        <Component {...pageProps} />;
      </motion.div>
    </>
  );
}

export default MyApp;
